In [ ]:
import pandas as pd
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
import numpy as np
import re
import os

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Explo/training.1600000.processed.noemoticon.csv', encoding='latin')

In [ ]:
head=['target', 'ID', 'Date', 'Flag', 'User', 'Message']
df.columns=head

In [ ]:
target=df['target']
target.value_counts()

4    800000
0    799999
Name: target, dtype: int64

In [ ]:
df.isnull().sum()

target     0
ID         0
Date       0
Flag       0
User       0
Message    0
dtype: int64

In [ ]:
df

,target,ID,Date,Flag,User,Message
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
...,...,...,...,...,...,...
1599994,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599995,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599996,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599997,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599998,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [ ]:
df.drop(columns=['ID', 'Date', 'User', 'Flag'], inplace=True)
df

         target                                            Message
0             0  is upset that he can't update his Facebook by ...
1             0  @Kenichan I dived many times for the ball. Man...
2             0    my whole body feels itchy and like its on fire
3             0  @nationwideclass no, it's not behaving at all....
4             0                      @Kwesidei not the whole crew
...         ...                                                ...
1599994       4  Just woke up. Having no school is the best fee...
1599995       4  TheWDB.com - Very cool to hear old Walt interv...
1599996       4  Are you ready for your MoJo Makeover? Ask me f...
1599997       4  Happy 38th Birthday to my boo of alll time!!! ...
1599998       4  happy #charitytuesday @theNSPCC @SparksCharity...

[1599999 rows x 2 columns]

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
stopword = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
import warnings
warnings.filterwarnings('ignore')
import re
import string
import pickle
urlPattern = r"((http://)[^ ]*|(https://)[^ ]*|( www\.)[^ ]*)"
userPattern = '@[^\s]+'
some = 'amp,today,tomorrow,going,girl'
def process_Message(Message):
  # Lower Casing
    Message = re.sub(r"he's", "he is", Message)
    Message = re.sub(r"there's", "there is", Message)
    Message = re.sub(r"We're", "We are", Message)
    Message = re.sub(r"That's", "That is", Message)
    Message = re.sub(r"won't", "will not", Message)
    Message = re.sub(r"they're", "they are", Message)
    Message = re.sub(r"Can't", "Cannot", Message)
    Message = re.sub(r"wasn't", "was not", Message)
    Message = re.sub(r"don\x89Ûªt", "do not", Message)
    Message = re.sub(r"aren't", "are not", Message)
    Message = re.sub(r"isn't", "is not", Message)
    Message = re.sub(r"What's", "What is", Message)
    Message = re.sub(r"haven't", "have not", Message)
    Message = re.sub(r"hasn't", "has not", Message)
    Message = re.sub(r"There's", "There is", Message)
    Message = re.sub(r"He's", "He is", Message)
    Message = re.sub(r"It's", "It is", Message)
    Message = re.sub(r"You're", "You are", Message)
    Message = re.sub(r"I'M", "I am", Message)
    Message = re.sub(r"shouldn't", "should not", Message)
    Message = re.sub(r"wouldn't", "would not", Message)
    Message = re.sub(r"i'm", "I am", Message)
    Message = re.sub(r"I\x89Ûªm", "I am", Message)
    Message = re.sub(r"I'm", "I am", Message)
    Message = re.sub(r"Isn't", "is not", Message)
    Message = re.sub(r"Here's", "Here is", Message)
    Message = re.sub(r"you've", "you have", Message)
    Message = re.sub(r"you\x89Ûªve", "you have", Message)
    Message = re.sub(r"we're", "we are", Message)
    Message = re.sub(r"what's", "what is", Message)
    Message = re.sub(r"couldn't", "could not", Message)
    Message = re.sub(r"we've", "we have", Message)
    Message = re.sub(r"it\x89Ûªs", "it is", Message)
    Message = re.sub(r"doesn\x89Ûªt", "does not", Message)
    Message = re.sub(r"It\x89Ûªs", "It is", Message)
    Message = re.sub(r"Here\x89Ûªs", "Here is", Message)
    Message = re.sub(r"who's", "who is", Message)
    Message = re.sub(r"I\x89Ûªve", "I have", Message)
    Message = re.sub(r"y'all", "you all", Message)
    Message = re.sub(r"can\x89Ûªt", "cannot", Message)
    Message = re.sub(r"would've", "would have", Message)
    Message = re.sub(r"it'll", "it will", Message)
    Message = re.sub(r"we'll", "we will", Message)
    Message = re.sub(r"wouldn\x89Ûªt", "would not", Message)
    Message = re.sub(r"We've", "We have", Message)
    Message = re.sub(r"he'll", "he will", Message)
    Message = re.sub(r"Y'all", "You all", Message)
    Message = re.sub(r"Weren't", "Were not", Message)
    Message = re.sub(r"Didn't", "Did not", Message)
    Message = re.sub(r"they'll", "they will", Message)
    Message = re.sub(r"they'd", "they would", Message)
    Message = re.sub(r"DON'T", "DO NOT", Message)
    Message = re.sub(r"That\x89Ûªs", "That is", Message)
    Message = re.sub(r"they've", "they have", Message)
    Message = re.sub(r"i'd", "I would", Message)
    Message = re.sub(r"should've", "should have", Message)
    Message = re.sub(r"You\x89Ûªre", "You are", Message)
    Message = re.sub(r"where's", "where is", Message)
    Message = re.sub(r"Don\x89Ûªt", "Do not", Message)
    Message = re.sub(r"we'd", "we would", Message)
    Message = re.sub(r"i'll", "I will", Message)
    Message = re.sub(r"weren't", "were not", Message)
    Message = re.sub(r"They're", "They are", Message)
    Message = re.sub(r"Can\x89Ûªt", "Cannot", Message)
    Message = re.sub(r"you\x89Ûªll", "you will", Message)
    Message = re.sub(r"I\x89Ûªd", "I would", Message)
    Message = re.sub(r"let's", "let us", Message)
    Message = re.sub(r"it's", "it is", Message)
    Message = re.sub(r"can't", "cannot", Message)
    Message = re.sub(r"don't", "do not", Message)
    Message = re.sub(r"you're", "you are", Message)
    Message = re.sub(r"i've", "I have", Message)
    Message = re.sub(r"that's", "that is", Message)
    Message = re.sub(r"i'll", "I will", Message)
    Message = re.sub(r"doesn't", "does not", Message)
    Message = re.sub(r"i'd", "I would", Message)
    Message = re.sub(r"didn't", "did not", Message)
    Message = re.sub(r"ain't", "am not", Message)
    Message = re.sub(r"you'll", "you will", Message)
    Message = re.sub(r"I've", "I have", Message)
    Message = re.sub(r"Don't", "do not", Message)
    Message = re.sub(r"I'll", "I will", Message)
    Message = re.sub(r"I'd", "I would", Message)
    Message = re.sub(r"Let's", "Let us", Message)
    Message = re.sub(r"you'd", "You would", Message)
    Message = re.sub(r"It's", "It is", Message)
    Message = re.sub(r"Ain't", "am not", Message)
    Message = re.sub(r"Haven't", "Have not", Message)
    Message = re.sub(r"Could've", "Could have", Message)
    Message = re.sub(r"youve", "you have", Message)  
    Message = re.sub(r"donå«t", "do not", Message)  
    
    Message = re.sub(r"some1", "someone", Message)
    Message = re.sub(r"yrs", "years", Message)
    Message = re.sub(r"hrs", "hours", Message)
    Message = re.sub(r"2morow|2moro", "tomorrow", Message)
    Message = re.sub(r"2day", "today", Message)
    Message = re.sub(r"4got|4gotten", "forget", Message)
    Message = re.sub(r"b-day|bday", "b-day", Message)
    Message = re.sub(r"mother's", "mother", Message)
    Message = re.sub(r"mom's", "mom", Message)
    Message = re.sub(r"dad's", "dad", Message)
    Message = re.sub(r"hahah|hahaha|hahahaha", "haha", Message)
    Message = re.sub(r"lmao|lolz|rofl", "lol", Message)
    Message = re.sub(r"thanx|thnx", "thanks", Message)
    Message = re.sub(r"goood", "good", Message)
    Message = re.sub(r"some1", "someone", Message)
    Message = re.sub(r"some1", "someone", Message)
    Message = Message.lower()
    Message = re.sub(urlPattern,'',Message)
    Message = re.sub(userPattern,'', Message) 
    Message= re.sub(some,'',Message)
    Message = Message.translate(str.maketrans("","",string.punctuation))
    tokens = word_tokenize(Message)
    final_tokens = [w for w in tokens if w not in stopword]
    wordLemm = WordNetLemmatizer()
    finalwords=[]
    for w in final_tokens:
      if len(w)>1:
        word = wordLemm.lemmatize(w)
        finalwords.append(word)
    return ' '.join(finalwords)

In [ ]:
df['FinalMessage'] = df['Message'].apply(lambda x: process_Message(x))

In [ ]:
df

,target,Message,FinalMessage
0,0,is upset that he can't update his Facebook by ...,upset update facebook texting might cry result...
1,0,@Kenichan I dived many times for the ball. Man...,dived many time ball managed save 50 rest go b...
2,0,my whole body feels itchy and like its on fire,whole body feel itchy like fire
3,0,"@nationwideclass no, it's not behaving at all....",behaving mad see
4,0,@Kwesidei not the whole crew,whole crew
...,...,...,...
1599994,4,Just woke up. Having no school is the best fee...,woke school best feeling ever
1599995,4,TheWDB.com - Very cool to hear old Walt interv...,thewdbcom cool hear old walt interview â
1599996,4,Are you ready for your MoJo Makeover? Ask me f...,ready mojo makeover ask detail
1599997,4,Happy 38th Birthday to my boo of alll time!!! ...,happy 38th birthday boo alll time tupac amaru ...
1599998,4,happy #charitytuesday @theNSPCC @SparksCharity...,happy charitytuesday

In [ ]:
df['Message']=df['FinalMessage']
df.drop(columns=['FinalMessage'], inplace=True)
df

         target                                            Message
0             0  upset update facebook texting might cry result...
1             0  dived many time ball managed save 50 rest go b...
2             0                    whole body feel itchy like fire
3             0                                   behaving mad see
4             0                                         whole crew
...         ...                                                ...
1599994       4                      woke school best feeling ever
1599995       4          thewdbcom cool hear old walt interview â
1599996       4                     ready mojo makeover ask detail
1599997       4  happy 38th birthday boo alll time tupac amaru ...
1599998       4                               happy charitytuesday

[1599999 rows x 2 columns]

In [ ]:
df.head(10)

   target                                            Message
0       0  upset update facebook texting might cry result...
1       0  dived many time ball managed save 50 rest go b...
2       0                    whole body feel itchy like fire
3       0                                   behaving mad see
4       0                                         whole crew
5       0                                           need hug
6       0  hey long time see yes rain bit bit lol fine th...
7       0                                               nope
8       0                                          que muera
9       0                    spring break plain city snowing

In [ ]:
df.to_csv('processed.csv')